# Generated by Django 5.0.3 on 2024-03-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('platter', 'Platter'), ('other', 'Other'), ('holiday_specials', 'Holiday Specials'), ('healthy_choices', 'Healthy Choices'), ('quick_and_easy', 'Quick & Easy'), ('budget_friendly', 'Budget-friendly'), ('comfort_food', 'Comfort Food'), ('international_cuisine', 'International Cuisine'), ('baking', 'Baking'), ('grilling_and_bbq', 'Grilling & BBQ'), ('vegetarian_vegan', 'Vegetarian/Vegan'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('whole30', 'Whole30'), ('mediterranean', 'Mediterranean'), ('asian_inspired', 'Asian-Inspired'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('middle_eastern', 'Middle Eastern')], default='other', max_length=25)),
                ('subcategory', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('keto', 'Keto'), ('other', 'Other'), ('paleo', 'Paleo-Friendly'), ('whole30', 'Whole30-Compliant'), ('mediterranean', 'Mediterranean Diet'), ('weight_loss', 'Weight Loss'), ('heart_healthy', 'Heart-Healthy'), ('diabetes_friendly', 'Diabetes-Friendly'), ('nut_free', 'Nut-Free'), ('soy_free', 'Soy-Free'), ('nutrient_dense', 'Nutrient-Dense'), ('light_and_fresh', 'Light & Fresh'), ('family_friendly', 'Family-Friendly'), ('kid_friendly', 'Kid-Friendly'), ('party_appetizers', 'Party Appetizers'), ('seasonal_produce', 'Seasonal Produce'), ('one_pot_meals', 'One-Pot Meals'), ('meal_prep', 'Meal Prep'), ('slow_cooker', 'Slow Cooker/Crockpot'), ('instant_pot', 'Instant Pot/Pressure Cooker'), ('raw_foods', 'Raw Foods'), ('superfoods', 'Superfoods'), ('detoxifying', 'Detoxifying'), ('immune_boosting', 'Immune-Boosting'), ('energy_packed', 'Energy-Packed')], default='other', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='Images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='MyRecipes.tag')),
            ],
        ),
    ]
