# Generated by Django 4.2.5 on 2024-03-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipes', '0005_alter_recipe_category_delete_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('platter', 'Platter'), ('other', 'Other'), ('holiday_specials', 'Holiday Specials'), ('healthy_choices', 'Healthy Choices'), ('healthy', 'Healthy '), ('quick_and_easy', 'Quick & Easy'), ('budget_friendly', 'Budget-friendly'), ('comfort_food', 'Comfort Food'), ('international_cuisine', 'International Cuisine'), ('baking', 'Baking'), ('grilling_and_bbq', 'Grilling & BBQ'), ('vegetarian_vegan', 'Vegetarian/Vegan'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('whole30', 'Whole30'), ('mediterranean', 'Mediterranean'), ('asian_inspired', 'Asian-Inspired'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('middle_eastern', 'Middle Eastern')], max_length=50),
        ),
    ]
