# Generated by Django 4.2.5 on 2024-03-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRecipes', '0007_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('platter', 'Platter'), ('other', 'Other'), ('holiday_specials', 'Holiday Specials'), ('healthy_choices', 'Healthy Choices'), ('healthy', 'Healthy'), ('budget_friendly', 'Budget-friendly'), ('comfort_food', 'Comfort Food'), ('international_cuisine', 'International Cuisine'), ('baking', 'Baking'), ('grilling_and_bbq', 'Grilling & BBQ'), ('vegetarian_vegan', 'Vegetarian/Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('whole30', 'Whole30'), ('mediterranean', 'Mediterranean'), ('asian_inspired', 'Asian-Inspired'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('middle_eastern', 'Middle Eastern'), ('new years', 'New Years'), ('mothers day', 'Mothers Day')], default='other', max_length=25),
        ),
    ]
